spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tim-phong-tro-ha-noi
    username: root
    password: "041202"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false